[package]
name = "bootstrapcicalculator"
version = "0.1.0"
authors = ["shane"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^0.13"
rand = "^0.8"
